version: '3'


# services:
#   postgres:
#     image: postgres:14.3
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_HOST: ${DB_HOST}   
#       POSTGRES_PORT: ${DB_PORT}    
#     container_name: teslodb
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     ports:
#       - "8080:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin    
#     depends_on:
#       - postgres

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data